version: '3.9'
services:
  web:
    build: .
    ports:
      - "8080:80"
    environment:
      - DB_HOST=mysql
      - DB_NAME=kgn_water_app
      - DB_USER=root
      - DB_PASS=secret
    depends_on:
      - mysql
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: kgn_water_app
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/01_schema.sql:ro
volumes:
  db_data:

